### ISSUE TITLE
ページタイトルに合わせてOGPのTitleなどが変更されない

### ISSUE THREAD

**Issue by yu-san-19** [student-lt/student-lt#42]
## 概要

例えば、
https://student-lt.tech/event/
を表示してシェアしても、
https://student-lt.tech/
を表示してシェアしても、
すべてSNSなどのシェアの際は「#学生LT - 学生エンジニア、集まれ。#学生LT は、学生エンジニアがお互いに繋がれる環境を作る為に立ち上がったコミュニティです。」みたいな感じになるので、
あまり親切でないなーと。

見た感じ、 https://student-lt.tech/event/ イベントのリンクなどは消滅して、Githubソース見ない限り
https://student-lt.tech/event/ にアクセスされることもないかもしれませんが、
もしこの先ページを増やすかもしれない時に参考までに... 😺 

## 個人的に思う解決策
 
Hugo の変数が用意されているのでその変数をもとに、
<meta property='og:title' content='{{ .Title }}'> みたいな感じでが良いのかなーと思います。

**Comment by kawashi** [comment]
すみません、イベントページは過去のものでリンクは削除し忘れで残ってしまっているものです💦
そのため現状はトップページのみしか存在しないため、このIssueは閉じて良いと思われます。

**Comment by yu-san-19** [comment]
@kawashi 
 #24 などで新ページができる可能性もありそうなので一応残してもらっておいてもよろしいかなーと思ったのですが...
わかりました 💦 
すみません。
