### ISSUE TITLE
デプロイを自動化したい

### ISSUE THREAD

**Issue by yakimelon** [student-lt/student-lt#54]
現状はいい感じのタイミングと環境で `./build.sh` を実行してデプロイしているが、これをCircleCI的な何かでマージしたらデプロイみたいな感じにしたい。(いい感じのタイミングと環境が整ってないと `./build.sh` はコケるし毎回実行するのも面倒)

そもそもCircleCIで実現出来るのかを調べるところから始める。

**Comment by MozyOk** [comment]
`.circleci/config.yml` などをつくって
以下のような感じで実行可能だと思う
```
deploy:
  command: |
    if [ "${CIRCLE_BRANCH}" == "gh-pages" ]; then
      *deploy command*
```

**Comment by OldBigBuddha** [comment]
[Netlfiy](https://www.netlify.com/) を利用したらいいんじゃないでしょうか？
ホスト対象のブランチを Netlify に登録して、そのブランチが更新されたら自動でビルドされますよ。

**Comment by tearaikazuki** [comment]
Netlifyで行ってるためClose
