### ISSUE TITLE
header.htmlと_index_header.htmlを統一

### ISSUE THREAD

**Issue by kawashi** [student-lt/student-lt#63]
両方あるとどちらかの変更を忘れてしまうので統一(今後ページが増えたらまた考えれば良い)

**Comment by yu-san-19** [comment]
勝手なこと言うとあれなのですけど、
SNS のアイコンとかはだいたいヘッダーじゃなくて、フッターに収まってるサイトが多い気がします。
なので、ヘッダーからフッターに移動するといいかも。
あと Font Awesome を使ったと方が圧倒的に楽になるかとも思いました。

**Comment by yu-san-19** [comment]
無言でPR送ってしまってすみません。
一応僕がやったことなので、僕が直しました〜。
